### ISSUE TITLE
Slow video looping on android devices

### ISSUE THREAD

**Issue by coulix** [expo/videoplayer#25]
It looks like the `isLooping` performs a full reload of the video (seek 0?) and freezes for a couple of seconds. Tested on two different androids. Ok on IOS.

expo: 2.23.1
expo-video: 0.40

``` <Video
          source={require('../../../assets/carotte4.mp4')} // eslint-disable-line
          rate={1.0}
          volume={0}
          isMuted
          isLooping
          resizeMode="cover"
          shouldPlay
          style={styles.video}
        />```

device video : https://storage.googleapis.com/greg_stuff/android_slug.mp4
video source : https://storage.googleapis.com/greg_stuff/carotte4.mp4
Test app: https://storage.googleapis.com/greg_stuff/android%252F%40gregt%252Fchefclub-d55d2e1e-3295-11e8-9770-0a580a782004-signed.apk

Other thing: is the vertical video has a resolution of 960x1440, it just does not load.

https://storage.googleapis.com/greg_stuff/carotte_960x1440.mp4

Did I miss anything? Is there a way to force caching a video in ram, or how can I pinpoint the origin of the freeze? IO activity monitoring on Android?

**Comment by joelpallagud** [comment]
Im having the same problem with my setup. Were you able to fix it?

**Comment by joelpallagud** [comment]
@sjchmiela @jesseruder Im sorry for tagging you here but i saw in issue #958 you have good knowledge on Expo.Video

**Comment by sjchmiela** [comment]
Sorry for the late response — indeed, at the moment Expo video player performs a _full reload of the video (seek 0)_. It will be fixed once we update the underlying Exoplayer dependency. 😞

**Comment by joelpallagud** [comment]
Is it the same dependency as react-native-video? Cause I remember using that in my previous project and looping works perfectly

**Comment by sjchmiela** [comment]
At the moment Expo uses a rather old version (_Updated Oct 17, 2016_) of ExoPlayer — 2.0.3, which does not implement [`setRepeatMode`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html#setRepeatMode-int-) yet. It has been introduced in https://github.com/google/ExoPlayer/commit/4d1826dd3d079338495a2e5d178c244580c7ad42, ExoPlayer 2.5.0.

I'll create an upstream issue about upgrading the ExoPlayer dependency. 🙂

**Comment by joelpallagud** [comment]
So that's why. Thank you very much for your good work! :)

**Comment by sjchmiela** [comment]
Ok, instead of creating an issue I've created a PR updating the dependency and its usage in the SDK. I think we can even make it to SDK 28. 🙂

**Comment by uholland** [comment]
It seems to be the same issue with expo 2.6.14 and expo client 32 on android. Is there any progress on this issue?
